//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctphieumuonsach
    {
        public int maPhieuMuonSach { get; set; }
        public int maSach { get; set; }
        public Nullable<int> tinhTrangSach { get; set; }
        public Nullable<int> soTienPhat { get; set; }
    
        public virtual phieumuonsach phieumuonsach { get; set; }
        public virtual sach sach { get; set; }
    }
}
