//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dausach
    {
        public int maDauSach { get; set; }
        public string tenDeMuc { get; set; }
        public string nhanDeChinh { get; set; }
        public string nhanDeSongSong { get; set; }
        public string nhanDeKhac { get; set; }
        public Nullable<int> lanXuatBan { get; set; }
        public string noiXuatBan { get; set; }
        public Nullable<int> namXuatBan { get; set; }
        public Nullable<int> soTrang { get; set; }
        public string khoSach { get; set; }
        public Nullable<int> soPhanLoai { get; set; }
        public string banQuyen { get; set; }
        public string ghiChu { get; set; }
        public string duLieuXepGia { get; set; }
        public Nullable<int> soLuong { get; set; }
        public string ngonNgu { get; set; }
        public Nullable<int> maNhaXuatBan { get; set; }
    
        public virtual nhaxuatban nhaxuatban { get; set; }
    }
}
