//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhaxuatban
    {
        public nhaxuatban()
        {
            this.dausach = new HashSet<dausach>();
        }
    
        public int maNhaXuatBan { get; set; }
        public string tenNXB { get; set; }
        public string diaDiem { get; set; }
    
        public virtual ICollection<dausach> dausach { get; set; }
    }
}
