//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThuVienEntities : DbContext
    {
        public ThuVienEntities()
            : base("name=ThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<anpham> anpham { get; set; }
        public DbSet<ctdonhang> ctdonhang { get; set; }
        public DbSet<ctphieumuonsach> ctphieumuonsach { get; set; }
        public DbSet<chude> chude { get; set; }
        public DbSet<dausach> dausach { get; set; }
        public DbSet<docgia> docgia { get; set; }
        public DbSet<donhang> donhang { get; set; }
        public DbSet<loainhanvien> loainhanvien { get; set; }
        public DbSet<nhacungcap> nhacungcap { get; set; }
        public DbSet<nhanvien> nhanvien { get; set; }
        public DbSet<nhaxuatban> nhaxuatban { get; set; }
        public DbSet<nhomdocgia> nhomdocgia { get; set; }
        public DbSet<phieumuonsach> phieumuonsach { get; set; }
        public DbSet<sach> sach { get; set; }
        public DbSet<tacgia> tacgia { get; set; }
        public DbSet<thethuvien> thethuvien { get; set; }
    }
}
