//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctdonhang
    {
        public int maAnPham { get; set; }
        public int maDonHang { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<int> donGia { get; set; }
    
        public virtual anpham anpham { get; set; }
        public virtual donhang donhang { get; set; }
    }
}
