//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class docgia
    {
        public int maDocGia { get; set; }
        public Nullable<int> MSSV { get; set; }
        public string maLop { get; set; }
        public string ho { get; set; }
        public string ten { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string gioiTinh { get; set; }
        public string diaChi { get; set; }
        public string SDT { get; set; }
        public Nullable<int> maTheThuVien { get; set; }
        public Nullable<int> maNhomDocGia { get; set; }
        public byte[] anhDaiDien { get; set; }
    
        public virtual thethuvien thethuvien { get; set; }
        public virtual nhomdocgia nhomdocgia { get; set; }
    }
}
