//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhacungcap
    {
        public nhacungcap()
        {
            this.donhangs = new HashSet<donhang>();
        }
    
        public int maNhaCungCap { get; set; }
        public string tenNhaCungCap { get; set; }
    
        public virtual ICollection<donhang> donhangs { get; set; }
    }
}
