//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class nhanvien
    {
        public nhanvien()
        {
            this.phieumuonsach = new HashSet<phieumuonsach>();
        }
    
        public int maNhanVien { get; set; }

        [Required(ErrorMessage="Vui lòng nhập tên đăng nhập", AllowEmptyStrings=false)]
        public string tenDangNhap { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mật khẩu", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string matKhau { get; set; }

        public string maLop { get; set; }
        public string ho { get; set; }
        public string ten { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string gioiTinh { get; set; }
        public string diaChi { get; set; }
        public string SDT { get; set; }
        public Nullable<int> LoaiNhanVien { get; set; }
    
        public virtual loainhanvien loainhanvien1 { get; set; }
        public virtual ICollection<phieumuonsach> phieumuonsach { get; set; }
    }
}
