//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhomdocgia
    {
        public nhomdocgia()
        {
            this.docgia = new HashSet<docgia>();
        }
    
        public int maNhomDocGia { get; set; }
        public string tenNhomDocGia { get; set; }
        public Nullable<int> soSachMuonToiDa { get; set; }
        public Nullable<int> thoiHanMuon { get; set; }
        public Nullable<int> thoiHanGiaHan { get; set; }
        public Nullable<int> thoiGianMuonQuaHan { get; set; }
        public Nullable<int> tienPhatMuonQuaHan { get; set; }
    
        public virtual ICollection<docgia> docgia { get; set; }
    }
}
