//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thethuvien
    {
        public thethuvien()
        {
            this.docgias = new HashSet<docgia>();
            this.phieumuonsaches = new HashSet<phieumuonsach>();
        }
    
        public int maTheThuVien { get; set; }
        public string maSoThe { get; set; }
        public string ngayHetHan { get; set; }
        public string trangThai { get; set; }
        public string ghiChu { get; set; }
        public Nullable<int> SLSachMuon { get; set; }
    
        public virtual ICollection<docgia> docgias { get; set; }
        public virtual ICollection<phieumuonsach> phieumuonsaches { get; set; }
    }
}
