//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThuVienEntities : DbContext
    {
        public ThuVienEntities()
            : base("name=ThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<anpham> anphams { get; set; }
        public DbSet<chude> chudes { get; set; }
        public DbSet<ctdonhang> ctdonhangs { get; set; }
        public DbSet<ctphieumuonsach> ctphieumuonsaches { get; set; }
        public DbSet<dausach> dausaches { get; set; }
        public DbSet<docgia> docgias { get; set; }
        public DbSet<donhang> donhangs { get; set; }
        public DbSet<loainhanvien> loainhanviens { get; set; }
        public DbSet<nhacungcap> nhacungcaps { get; set; }
        public DbSet<nhanvien> nhanviens { get; set; }
        public DbSet<nhaxuatban> nhaxuatbans { get; set; }
        public DbSet<nhomdocgia> nhomdocgias { get; set; }
        public DbSet<phieumuonsach> phieumuonsaches { get; set; }
        public DbSet<sach> saches { get; set; }
        public DbSet<tacgia> tacgias { get; set; }
        public DbSet<thethuvien> thethuviens { get; set; }
    }
}
